# Generated by Django 4.2 on 2024-04-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_gender_alter_user_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
